#!/bin/sh
rm -rf /usr/share/enigma2/GlamourAuraRose
echo "                                                                   "
echo "Glamour Aura Rose skin was successfully removed from your receiver."