#!/bin/sh
echo "                                   *******                                  "
echo "                         ******               *****                         "
echo "                    ****                            ****                    "
echo "                 ***                                     ***                "
echo "               **     GLAMOUR AURA ROSE SKIN FOR OPENPLI    **              "
echo "                            a skin by MCelliotG                             "
echo "                                                                            "
echo "                                                                            "
echo "                         ***** DISCLAIMER ****                              "
echo "Glamour Aura Rose skin requires a minimal dual core CPU @ 751Mhz.           "
echo "Glamour Aura Rose is NOT guaranteed to work on slower or older receivers.   "
echo "                                                                            "
echo "                                                                            "
echo "                                                                            "
echo "                                                                            "
echo "Checking if a previous version of Glamour Aura Rose skin is installed"
if [ -f /usr/share/enigma2/GlamourAuraRose/skin.xml ]; then
    cp -R /usr/share/enigma2/GlamourAuraRose/ /tmp
    rm -rf /usr/share/enigma2/GlamourAuraRose
    rm -rf /usr/lib/enigma2/python/Components/Converter/Glam*
    rm -rf /usr/lib/enigma2/python/Components/Renderer/Glam*
    echo "                                              "
    echo "Previous GlamourAuraRose skin installation    "
    echo "    was found and removed successfully!       "
    echo "                                              "
fi
echo "                                                  "
echo "Glamour Aura Rose skin is now being installed...  "
echo "                                                  "
