#!/bin/sh
echo "                                                               "
echo "Glamour Aura Rose skin is now being removed from your receiver."
echo "                                                               "
